version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: bin/app-stop
      timeout: 10
      runas: ec2-user
      
  AfterInstall:
    - location: installPack.sh
      timeout: 1200
      runas: ec2-user

  ApplicationStart:
    - location: app-start.sh
      timeout: 3500
      runas: ec2-user
 
  ValidateService:
    - location: bin/app-validate
      timeout: 10
      runas: ec2-user
